use_frameworks!

target 'RxSmartBag_Example' do
  pod 'RxSmartBag', :path => '../'

  target 'RxSmartBag_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
